/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Webonise' at '31/5/17 11:07 PM' with Gradle 2.3
 *
 * @author Webonise, @date 31/5/17 11:07 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
